FROM node:22-alpine AS base
RUN corepack enable

FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_SOCKET_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_COMPANION_URL
ARG NEXT_PUBLIC_MIRROR_ID
ARG NEXT_PUBLIC_KIOSK_DEVICE_SECRET
ARG NEXT_PUBLIC_MAPBOX_TOKEN
ARG NEXT_PUBLIC_DEVICE_MODE
ARG NEXT_PUBLIC_DOMAIN1
ARG NEXT_PUBLIC_DOMAIN2
ARG NEXT_PUBLIC_USER1_ACCESS_TOKEN
ARG NEXT_PUBLIC_USER1_REFRESH_TOKEN
ARG NEXT_PUBLIC_USER2_ACCESS_TOKEN
ARG NEXT_PUBLIC_USER2_REFRESH_TOKEN
ARG NEXT_PUBLIC_MODEL_MALE_URL
ARG NEXT_PUBLIC_MODEL_FEMALE_URL

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL \
    NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL \
    NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_COMPANION_URL=$NEXT_PUBLIC_COMPANION_URL \
    NEXT_PUBLIC_MIRROR_ID=$NEXT_PUBLIC_MIRROR_ID \
    NEXT_PUBLIC_KIOSK_DEVICE_SECRET=$NEXT_PUBLIC_KIOSK_DEVICE_SECRET \
    NEXT_PUBLIC_MAPBOX_TOKEN=$NEXT_PUBLIC_MAPBOX_TOKEN \
    NEXT_PUBLIC_DEVICE_MODE=$NEXT_PUBLIC_DEVICE_MODE \
    NEXT_PUBLIC_DOMAIN1=$NEXT_PUBLIC_DOMAIN1 \
    NEXT_PUBLIC_DOMAIN2=$NEXT_PUBLIC_DOMAIN2 \
    NEXT_PUBLIC_USER1_ACCESS_TOKEN=$NEXT_PUBLIC_USER1_ACCESS_TOKEN \
    NEXT_PUBLIC_USER1_REFRESH_TOKEN=$NEXT_PUBLIC_USER1_REFRESH_TOKEN \
    NEXT_PUBLIC_USER2_ACCESS_TOKEN=$NEXT_PUBLIC_USER2_ACCESS_TOKEN \
    NEXT_PUBLIC_USER2_REFRESH_TOKEN=$NEXT_PUBLIC_USER2_REFRESH_TOKEN \
    NEXT_PUBLIC_MODEL_MALE_URL=$NEXT_PUBLIC_MODEL_MALE_URL \
    NEXT_PUBLIC_MODEL_FEMALE_URL=$NEXT_PUBLIC_MODEL_FEMALE_URL

RUN npm run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production PORT=3000
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
